### PR TITLE
Export framework as a module

### PR DESCRIPTION
**Pull request by ghost**
This way, we can import the framework using

```
npm install --save madmurphy/cookies.js

import cookies from 'cookies.js'
```

### CODE REVIEW

**Comment by madmurphy** [comment]
Hi pdme!

The idea is good in theory, but would make cookies.js npm-centric. Any idea for solving this problem?

**Comment by ghost** [comment]
Do you mean it would throw an error if loaded directly in the browser?

We could solve it by checking if module exists before exporting.

I updated the pull request.

**Review by madmurphy — APPROVED** [review]
Good job. Approved :)

**Comment by ghost** [comment]
Great, thanks :)

**Pull request merged**
