### PR TITLE
Add Grunt plugins to minify the JS and generate source map file.

### PR DESCRIPTION
**Pull request by rvalitov**
### What's new:
- Minification of JS. Now the developers can easily minify the JS right from the IDE.
- Source map file. A source map file is now generated.
- The usage instructions for developers are injected into the README. 
- The minified file is called now `cookies.min.js`. The old `cookies_min.js` file is removed.
- `.gitignore` file added to ignore most common files which are used by IDE or OS and should not be a part of any commits.

### CODE REVIEW

**Comment by rvalitov** [comment]
Closes #14

**Comment by madmurphy** [comment]
@rvalitov

Thank you! I will be busy until next week, but at first sight it seems OK. I will have a better look in the next days.

--madmurphy

**Comment by rvalitov** [comment]
@madmurphy did you have time to look into this?:)

**Comment by madmurphy** [comment]
@rvalitov

Hard times… Merged!

**Pull request merged**
